<?php

namespace Oenoweb\OenowebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CaracteristiquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracteristiquesRepository extends EntityRepository
{
}
