<?php

namespace Oenoweb\OenowebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CepageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CepageRepository extends EntityRepository
{
}
