<?php

namespace Oenoweb\OenowebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CepageVinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CepageVinsRepository extends EntityRepository
{
}
