<?php

namespace Oenoweb\OenowebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Couleur_appellationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Couleur_appellationRepository extends EntityRepository
{
}
