<?php

namespace Oenoweb\OenowebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VinsRepository extends EntityRepository
{
}
