users : 
  type : rest
  resource :     "OenowebBundle:OenowebRest"
  name_prefix :  api_

vins :
  type : rest
  resource :     "OenowebBundle:RechercheDidactiqueRest"
  name_prefix :  api_ 

  resource :     "OenowebBundle:VinsRest"
  name_prefix :  api_

social :
  type : rest
  resource : "OenowebBundle:FonctionSocialeRest"
  name_prefix : api_
  requirements :
    _method: POST|GET

synchro :
  type : rest
  resource : "OenowebBundle:SynchronisationRest"
  name_prefis : api_


deleteavis :
  type : rest
  resource : "OenowebBundle:DeleteAvisRest"
  name_prefix : api_
  requirements :
    _method: DELETE|GET