oenoweb_homepage:
    path:     /hello
    defaults: { _controller: OenowebBundle:Default:index }


test:
    path:     /create
    defaults: { _controller: OenowebBundle:Test:create }


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"