users : 
  type : rest
  resource :     "OenowebBundle:OenowebRest"
  name_prefix :  api_

avisgetnomvins : 
  type : rest
  resource :     "OenowebBundle:AfficherAvisRest"
  name_prefix :  api_

avispost : 
  type : rest
  resource :     "OenowebBundle:AvisPostRest"
  name_prefix :  api_
  requirements :
     _method: POST|GET

favoris :
  type : rest
  resource :     "OenowebBundle:FavorisPostRest"
  name_prefix :  api_
  requirements :
     _method: POST|GET

vins :
  type : rest

  resource :     "OenowebBundle:RechercheDidactiqueRest"
  name_prefix :  api_ 

  resource :     "OenowebBundle:VinsRest"
  name_prefix :  api_

avisgetnomuser : 
  type : rest
  resource :     "OenowebBundle:AfficherAvisUserRest"
  name_prefix :  api_

synchro :
  type : rest
  resource : "OenowebBundle:SynchronisationRest"
  name_prefis : api_