users : 
  type : rest
  resource :     "OenowebBundle:OenowebRest"
  name_prefix :  api_
  requirements:
     _scheme:  https


region : 
  type : rest
  resource :     "OenowebBundle:VinsRegionRest"
  name_prefix :  api_

aoc : 
  type : rest
  resource :     "OenowebBundle:VinsAocRest"
  name_prefix :  api_

domaine : 
  type : rest
  resource :     "OenowebBundle:VinsDomaineRest"
  name_prefix :  api_

avis : 
  type : rest
  resource :     "OenowebBundle:AfficherAvisRest"
  name_prefix :  api_

avis : 
  type : rest
  resource :     "OenowebBundle:PosterUnAvisRestRest"
  name_prefix :  api_

favoris :
  type : rest
  pattern:  /
  defaults: { _controller: OenowebBundle:FavorisRest:post }