users : 
  type : rest
  resource :     "OenowebBundle:OenowebRest"
  name_prefix :  api_

avisget : 
  type : rest
  resource :     "OenowebBundle:AfficherAvisRest"
  name_prefix :  api_

avispost : 
  type : rest
  resource :     "OenowebBundle:AvisPostRest"
  name_prefix :  api_
  requirements :
     _method: POST|GET

favoris :
  type : rest
  resource :     "OenowebBundle:FavorisPostRest"
  name_prefix :  api_
  requirements :
     _method: POST|GET

vins :
  type : rest

  resource :     "OenowebBundle:RechercheDidactiqueRest"
  name_prefix :  api_ 
